### ISSUE TITLE
Add a note about string normalization before match it with p{IsCombiningDiacriticalMarks}

### ISSUE THREAD

**Issue by brud** [dotnet/docs.ru-ru#313] opened 2020-10-26 22:19 UTC
I think it would be a good idea to add a note about normalization the string to D form before matching it with `@"\p {IsCombiningDiacriticalMarks}"` - it could save a ton of time for newbies.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a1958bf6-a17d-1256-d659-31066aa02604
* Version Independent ID: 95abea42-fa7f-3feb-ae38-049719ab938f
* Content: [Классы символов в регулярных выражениях .NET](https://docs.microsoft.com/ru-ru/dotnet/standard/base-types/character-classes-in-regular-expressions)
* Content Source: [docs/standard/base-types/character-classes-in-regular-expressions.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/standard/base-types/character-classes-in-regular-expressions.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2020-11-02 21:14
Duplicate of https://github.com/dotnet/docs/issues/21237

**Closed by adegeo** 2020-11-02 21:14 UTC
